#! /bin/bash

TIMESTAMP=$( date +%s )

/usr/bin/mysql --defaults-extra-file=/database/local.cnf -h $LOCAL_MYSQL_HOST $LOCAL_MYSQL_DATABASE < /database/database.sql

TOTAL=$( expr $( date +%s ) - $TIMESTAMP)
echo "LOCAL DATABASE IMPORTED IN ${TOTAL} SECONDS"
