#! /bin/bash

if [ "$FIREBASE_ACTIVE" = "1" ]; then

  echo "DEPLOY FIREBASE"

  cd /firebase
  firebase use $FIREBASE_PROJECT --token ${FIREBASE_TOKEN}

  echo "SERVER=PRODUCTION_RUNNER" > /web/environments/server.env

  if [ "$FIREBASE_TARGET" == "functions" ]; then

    cd /firebase/functions
    npm install
    
    echo "DEPLOYING FUNCTIONS"
    cd /firebase
    firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token ${FIREBASE_TOKEN} --only functions
  
  else

    if [ ! -z "$FIREBASE_PREVIEW" ]; then # not empty
    
      if [ ! -z "$FIREBASE_CLONE" ]; then

        firebase hosting:clone $FIREBASE_PROJECT:$FIREBASE_PREVIEW $FIREBASE_PROJECT:$FIREBASE_CLONE --token ${FIREBASE_TOKEN}

      else

        firebase hosting:channel:deploy $FIREBASE_PREVIEW --token ${FIREBASE_TOKEN}

      fi
    
    else
    
      firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token ${FIREBASE_TOKEN} --only hosting

    fi

  
  fi

fi
